### ISSUE TITLE
Issue in Homme's VerticalRemapManager

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1133]
Homme handles flags in a particular way. In particular, it does not use info from `CMAKE_BUILD_TYPE` to establish its optimization flags. The way to go to select an opt level for Homme is to use the cmake var `OPT_FLAGS`. So, if you don't set anything, the homme lib (e.g., `theta-l_kokkos_4_72_4`) is built with `-O3` as last opt flag.

I tried to set `OPT_FLAGS="-O0"`, to force homme to be built without optimizations, and the homme tests started to crash, with a segfault error due to a ptr being null. In particular, I get this backtrace (snippet):

```
#3  0x00007ffff495b252 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x000000000157a8b6 in Homme::VerticalRemapManager::requested_buffer_size (this=0x25479e0)
    at /home/luca/workdir/scream/scream-src/branch/components/homme/src/share/cxx/VerticalRemapManager.cpp:140
#5  0x00000000011ad21f in scream::HommeDynamics::requested_buffer_size_in_bytes (this=0x20c2610)
    at /home/luca/workdir/scream/scream-src/branch/components/scream/src/dynamics/homme/atmosphere_dynamics.cpp:259
```

Looking at the code, the error seems legit: we have not yet fully init-ed the VerticalRemapManager, so we don't have access to the Remap object yet. And yet, the assert at the beginning of `requested_buffer_size` is checking precisely that.

Solution: move the assert inside the `if (is_setup)` block.

Note: this fix needs to be then put in the e3sm pr with all the homme changes.

**Comment by bartgol** [comment]
This was fixed by #1134
