### ISSUE TITLE
illegal memory access with v1 cime case (presumably in radiation)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1474]
With a repo of March 12th, 
which is after
`f161bcee2a 2022-03-11 12:53:17 -0800 Merge pull request #1419 from E3SM-Project/brhillman/scream/enable-rrtmgp-aerosol`

I see a new error with the cime case I'm trying. `SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.perlmutter_gnugpu`
I see the error below in DEBUG and it stop in same location without DEBUG.

```
0: IMEX max iterations, error:  0  0.000000000000000E+00  0.000000000000000E+00
0: terminate called after throwing an instance of 'std::runtime_error'
0:   what():  cudaStreamSynchronize(stream) error( cudaErrorIllegalAddress): an illegal memory access was encountered /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:161
0: Traceback functionality not available
0:
0:
0: Program received signal SIGABRT: Process abort signal.
0:
0: Backtrace for this error:
0: #0  0x14ca78b983df in ???
0: #1  0x14ca78b98360 in ???
0: #2  0x14ca78b99940 in ???
0: #3  0x14ca7ef01f59 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv
0:      at ../../../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/libstdc++-v3/libsupc++/vterminate.cc:95
0: #4  0x14ca7ef0d7b9 in _ZN10__cxxabiv111__terminateEPFvvE
0:      at ../../../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/libstdc++-v3/libsupc++/eh_terminate.cc:48
0: #5  0x14ca7ef0d824 in _ZSt9terminatev
0:      at ../../../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/libstdc++-v3/libsupc++/eh_terminate.cc:58
0: #6  0x14ca7ef0dab7 in __cxa_throw
0:      at ../../../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/libstdc++-v3/libsupc++/eh_throw.cc:95
0: #7  0x3294f68 in _ZN6Kokkos4Impl23throw_runtime_exceptionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/impl/Kokkos_Error.cpp:72
0: #8  0x32a45e1 in _ZN6Kokkos4Impl25cuda_internal_error_throwE9cudaErrorPKcS3_i
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:183
0: #9  0x5c9003 in _ZN6Kokkos4Impl23cuda_internal_safe_callE9cudaErrorPKcS3_i
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:73
0: #10  0x32a441f in operator()
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:161
0: #11  0x32a7334 in profile_fence_event<Kokkos::Cuda, Kokkos::Impl::cuda_stream_synchronize(cudaStream_t, const Kokkos::Impl::CudaInternal*, const string&)::<lambda()> >
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/impl/Kokkos_Profiling.hpp:180
0: #12  0x32a445f in _ZN6Kokkos4Impl23cuda_stream_synchronizeEP11CUstream_stPKNS0_12CudaInternalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:156
0: #13  0x32a4c9f in _ZNK6Kokkos4Impl12CudaInternal5fenceERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:345
0: #14  0x308483d in _ZN6Kokkos4Impl22CudaParallelLaunchImplINS0_11ParallelForI18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIMN6scream15RRTMGPRadiationEFviEXadL_ZNS6_8run_implEiEELj1EEFvRKNS0_14CudaTeamMemberEEJNS_4ViewIPPKdJNS_11LayoutRightENS_6DeviceINS_4CudaENS_9CudaSpaceEEENS_12MemoryTraitsILj0EEEEEESP_NSE_IPPdJSI_SM_SO_EEE\
SP_SS_SS_KiNSE_ISG_JSI_SM_SO_EEESF_N4yakl5ArrayIdLi1ELi1ELi2EEENSE_ISQ_JSI_SM_NSN_ILj1EEEEEESX_SU_SX_SU_SX_SU_SX_SU_NSW_IdLi2ELi1ELi2EEES10_S10_S10_SP_S10_SP_S10_SP_S10_SP_S10_SP_S10_SP_S1^@^A^@^@^@^@^@^@^@^N^@^@^@^@^@^@^@=H^H^C^@^@^@^@9@]\351\311^T^@^@9@]\351\311^T^@^@\360!^E\277\377^?^@^@\240\326>\364\311^T^@^@\240\326>\36\
4\311^T^@^@^X^@^@^@^@^@^@^@\356^_\264y\312^T^@^@^@^@^@^@^@^@^@^@\320\276\263y\312^T^@^@^@\3602\364\311^T^@^@^A^@^@^@^@^@^@^@^B^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^X\327>\364\311^T^@^@^X\327>\364\311^T^@^@^X^@^@^@^@^@^@^@\356^_\264y\312^T^@^@^A^@^@^@^@^@^@^@\320\276\263y\312^T^@^@9@]\351\311^T^@^@h?\217y\312^T^@^@^@\300=\364\311^T^\
@^@X\301A\364\311^T^@^@^@\300=\364\311^T^@^@=H^H^C^@^@^@^@^@\313^Qp\312^T^@   at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp:645
0: #15  0x307fbab in _ZN6Kokkos4Impl18CudaParallelLaunchINS0_11ParallelForI18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIMN6scream15RRTMGPRadiationEFviEXadL_ZNS6_8run_implEiEELj1EEFvRKNS0_14CudaTeamMemberEEJNS_4ViewIPPKdJNS_11LayoutRightENS_6DeviceINS_4CudaENS_9CudaSpaceEEENS_12MemoryTraitsILj0EEEEEESP_NSE_IPPdJSI_SM_SO_EEESP_S\
S_SS_KiNSE_ISG_JSI_SM_SO_EEESF_N4yakl5ArrayIdLi1ELi1ELi2EEENSE_ISQ_JSI_SM_NSN_ILj1EEEEEESX_SU_SX_SU_SX_SU_SX_SU_NSW_IdLi2ELi1ELi2EEES10_S10_S10_SP_S10_SP_S10_SP_S10_SP_S10_SP_S10_SP_S10_KP^@^A^@^@^@^@^@^@^@^O^@^@^@^@^@^@^@\253\373^G^C^@^@^@^@I\335]\351\311^T^@^@I\335]\351\311^T^@^@\360!^E\277\377^?^@^@\240\326>\364\311^T^@^@\
\240\326>\364\311^T^@^@^X^@^@^@^@^@^@^@\356^_\264y\312^T^@^@^@^@^@^@^@^@^@^@\320\276\263y\312^T^@^@^@\3602\364\311^T^@^@^A^@^@^@^@^@^@^@^B^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^X\327>\364\311^T^@^@^X\327>\364\311^T^@^@^X^@^@^@^@^@^@^@\356^_\264y\312^T^@^@^A^@^@^@^@^@^@^@\320\276\263y\312^T^@^@I\335]\351\311^T^@^@h?\217y\312^T^@^@^@\\
300=\364\311^T^@^@P=B\364\311^T^@^@^@^@#\364\311^T^@^@\253\373^G^C^@^@^@^@^@\313^Qp\312       at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp:693
0: #16  0x3079803 in _ZNK6Kokkos4Impl11ParallelForI18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIMN6scream15RRTMGPRadiationEFviEXadL_ZNS5_8run_implEiEELj1EEFvRKNS0_14CudaTeamMemberEEJNS_4ViewIPPKdJNS_11LayoutRightENS_6DeviceINS_4CudaENS_9CudaSpaceEEENS_12MemoryTraitsILj0EEEEEESO_NSD_IPPdJSH_SL_SN_EEESO_SR_SR_KiNSD_ISF_JSH_SL_SN\
_EEESE_N4yakl5ArrayIdLi1ELi1ELi2EEENSD_ISP_JSH_SL_NSM_ILj1EEEEEESW_ST_SW_ST_SW_ST_SW_ST_NSV_IdLi2ELi1ELi2EEESZ_SZ_SZ_SO_SZ_SO_SZ_SO_SZ_SO_SZ_SO_SZ_SO_SZ_KPS5_NSV_IdLi3ELi1ELi2EEENSD_IPSG_J^@^A^@^@^@^@^@^@^@^P^@^@^@^@^@^@^@^C\230^G^C^@^@^@^@\3748\\351\311^T^@^@\3748\\351\311^T^@^@\360!^E\277\377^?^@^@\240\326>\364\311^T^@^@\2\
40\326>\364\311^T^@^@^X^@^@^@^@^@^@^@\356^_\264     at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp:768
0: #17  0x3074c49 in _ZN6Kokkos12parallel_forINS_10TeamPolicyIJNS_4CudaEEEE18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIMN6scream15RRTMGPRadiationEFviEXadL_ZNS7_8run_implEiEELj1EEFvRKNS_4Impl14CudaTeamMemberEEJNS_4ViewIPPKdJNS_11LayoutRightENS_6DeviceIS2_NS_9CudaSpaceEEENS_12MemoryTraitsILj0EEEEEESQ_NSG_IPPdJSK_SN_SP_EEESQ_ST_\
ST_KiNSG_ISI_JSK_SN_SP_EEESH_N4yakl5ArrayIdLi1ELi1ELi2EEENSG_ISR_JSK_SN_NSO_ILj1EEEEEESY_SV_SY_SV_SY_SV_SY_SV_NSX_IdLi2ELi1ELi2EEES11_S11_S11_SQ_S11_SQ_S11_SQ_S11_SQ_S11_SQ_S11_SQ_S11_KPS7^@^A^@^@^@^@^@^@^@^Q^@^@^@^@^@^@^@IL^G^C^@^@^@^@\304g[\351\311^T^@^@\304g[\351\311^T^@^@\360!^E\277\377^?^@^@\240\326>\364\311^T^@^@\240\3\
26>\364\311^T^@^@^X^@^@^@^@^@^@^@\356^_\264y\312^T^@^@^@^@^@^@^@^@^@^@\320\276\263y\312^T^@^@^@\3602\364\311^T^@^@^A^@^@^@^@^@^@^@^B^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^X\327>\364\311^T^@^@^X\327>\364\311^T^@^@^X^@^@^@^@^@^@^@\356^_\264y\312^T^@^@^A^@^@^@^@^@^@^@\320\276\263y\312^T^@^@\304g[\351\311^T^@^@h?\217y\312^T^@^@^@\300=\3\
64\311^T^@    at /pscratch/sd/n/ndk/wacmy/s14-mar12/externals/ekat/extern/kokkos/core/src/Kokkos_Parallel.hpp:142
0: #18  0x305d0d3 in _ZN6scream15RRTMGPRadiation8run_implEi
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp:415
0: #19  0x31892e7 in _ZN6scream17AtmosphereProcess3runEi
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/share/atm_process/atmosphere_process.cpp:46
0: #20  0x3198e13 in _ZN6scream22AtmosphereProcessGroup14run_sequentialEd
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/share/atm_process/atmosphere_process_group.cpp:158
0: #21  0x3198d23 in _ZN6scream22AtmosphereProcessGroup8run_implEi
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/share/atm_process/atmosphere_process_group.cpp:145
0: #22  0x31892e7 in _ZN6scream17AtmosphereProcess3runEi
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/share/atm_process/atmosphere_process.cpp:46
0: #23  0x256285e in _ZN6scream7control16AtmosphereDriver3runEi
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/control/atmosphere_driver.cpp:802
0: #24  0x5c27f1 in operator()
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp:204
0: #25  0x5c7444 in fpe_guard_wrapper<scream_run(const Real&)::<lambda()> >
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp:50
0: #26  0x5c2814 in scream_run
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp:201
0: #27  0x5be894 in __atm_comp_mct_MOD_atm_run_mct
0:      at /pscratch/sd/n/ndk/wacmy/s14-mar12/components/scream/src/mct_coupling/atm_comp_mct.F90:209
```

I verified that the repo before that last PR noted above does not have this issue.

**Comment by bartgol** [comment]
This might be related to our cuda-memcheck build failing. When issuing a PR to fix those, we'll make sure to link this issue.
