### ISSUE TITLE
Summit GPU debugging: 2 tasks on same node

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/scream#1681]
v1 ne4 crashes during initialization using 2 tasks on a single node. We get a core dump

Even disabling GPU-aware MPI didn't help.  I suspected GPU to GPU communication issue. So, I tried a flag to disable fast GPU Peer-to-peer communication but that still crashed (PAMI_DISABLE_IPC=1)

The last thing from app side is
`#16 0x0000000012f5631c in Homme::BoundaryExchange::recv_and_unpack (this=0x3ee45a40, rspheremp=0x0) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/homme/src/share/cxx/mpi/BoundaryExchange.cpp:555`

cc @bartgol @oksanaguba @jgfouca @whannah1 

Backtrace of the stuck process
```
(gdb) bt
#0  0x0000200006103618 in raise () from /lib64/power9/libc.so.6
#1  0x00002000060e3a2c in abort () from /lib64/power9/libc.so.6
#2  0x00002000060f6f70 in __assert_fail_base () from /lib64/power9/libc.so.6
#3  0x00002000060f7014 in __assert_fail () from /lib64/power9/libc.so.6
#4  0x000020000a2560b8 in PAMI::Protocol::Get::GetRdma<PAMI::Device::Shmem::DmaModel<PAMI::Device::ShmemDevice<PAMI::Fifo::WrapFifo<PAMI::Fifo::FifoPacket<64u, 4096u>, PAMI::Counter::IndirectBounded<PAMI::Atomic::NativeAtomic>, 256u>, PAMI::Counter::Indirect<PAMI::Counter::Native>, PAMI::Device::Shmem::CMAShaddr, 256u, 512u>, false>, PAMI::Device::ShmemDevice<PAMI::Fifo::WrapFifo<PAMI::Fifo::FifoPacket<64u, 4096u>, PAMI::Counter::IndirectBounded<PAMI::Atomic::NativeAtomic>, 256u>, PAMI::Counter::Indirect<PAMI::Counter::Native>, PAMI::Device::Shmem::CMAShaddr, 256u, 512u> >::simple(pami_rget_simple_t*) ()
   from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/pami_port/libpami.so.3
#5  0x000020000a1ac590 in PAMI::Protocol::Get::CompositeRGet<PAMI::Protocol::Get::RGet, PAMI::Protocol::Get::RGet>::simple(pami_rget_simple_t*) () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/pami_port/libpami.so.3
#6  0x000020000a1da05c in PAMI::Context::rget_impl(pami_rget_simple_t*) () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/pami_port/libpami.so.3
#7  0x000020000a198e38 in PAMI_Rget () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/pami_port/libpami.so.3
#8  0x0000200008fd59ec in process_rndv_msg () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/spectrum_mpi/mca_pml_pami.so
#9  0x0000200008fd674c in pml_pami_recv_rndv_cb () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/spectrum_mpi/mca_pml_pami.so
#10 0x000020000a1a2a2c in PAMI::Protocol::Send::EagerSimple<PAMI::Device::Shmem::PacketModel<PAMI::Device::ShmemDevice<PAMI::Fifo::WrapFifo<PAMI::Fifo::FifoPacket<64u, 4096u>, PAMI::Counter::IndirectBounded<PAMI::Atomic::NativeAtomic>, 256u>, PAMI::Counter::Indirect<PAMI::Counter::Native>, PAMI::Device::Shmem::CMAShaddr, 256u, 512u> >, (PAMI::Protocol::Send::configuration_t)5>::dispatch_packed(void*, void*, unsigned long, void*, void*) () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/pami_port/libpami.so.3
#11 0x000020000a199ec0 in PAMI_Context_advancev () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/pami_port/libpami.so.3
#12 0x0000200008fc7424 in mca_pml_pami_progress () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/spectrum_mpi/mca_pml_pami.so
#13 0x00002000070b610c in opal_progress () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/libopen-pal.so.3
#14 0x0000200005e61064 in ompi_request_default_wait_all () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/libmpi_ibm.so.3
#15 0x0000200005ec216c in PMPI_Waitall () from /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/container/../lib/libmpi_ibm.so.3
#16 0x0000000012f5631c in Homme::BoundaryExchange::recv_and_unpack (this=0x3ee45a40, rspheremp=0x0) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/homme/src/share/cxx/mpi/BoundaryExchange.cpp:555
#17 0x0000000012f5200c in Homme::BoundaryExchange::exchange (this=0x3ee45a40, rspheremp=0x0) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/homme/src/share/cxx/mpi/BoundaryExchange.cpp:268
#18 0x0000000012f51d70 in Homme::BoundaryExchange::exchange (this=0x3ee45a40) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/homme/src/share/cxx/mpi/BoundaryExchange.cpp:232
#19 0x0000000012a29e28 in scream::PhysicsDynamicsRemapper::do_remap_fwd (this=0x3eb1abe0) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/dynamics/homme/physics_dynamics_remapper.cpp:474
#20 0x0000000013866d58 in scream::AbstractRemapper::remap (this=0x3eb1abe0, forward=true) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/share/grid/remap/abstract_remapper.cpp:128
#21 0x000000001292941c in scream::HommeDynamics::initialize_homme_state (this=0x39e23470) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/dynamics/homme/atmosphere_dynamics.cpp:1006
#22 0x000000001291d15c in scream::HommeDynamics::initialize_impl (this=0x39e23470, run_type=scream::RunType::Initial) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/dynamics/homme/atmosphere_dynamics.cpp:367
#23 0x00000000137b53f4 in scream::AtmosphereProcess::initialize (this=0x39e23470, t0=..., run_type=scream::RunType::Initial) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/share/atm_process/atmosphere_process.cpp:43
#24 0x00000000137d0888 in scream::AtmosphereProcessGroup::initialize_impl (this=0x3ac59e10, run_type=scream::RunType::Initial) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/share/atm_process/atmosphere_process_group.cpp:186
#25 0x00000000137b53f4 in scream::AtmosphereProcess::initialize (this=0x3ac59e10, t0=..., run_type=scream::RunType::Initial) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/share/atm_process/atmosphere_process.cpp:43
#26 0x000000001265db50 in scream::control::AtmosphereDriver::initialize_atm_procs (this=0x3f1e9630) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/control/atmosphere_driver.cpp:872
#27 0x000000001024ac70 in <lambda()>::operator()(void) const (__closure=0x7fffd90372b0) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp:190
#28 0x0000000010252c04 in _GLOBAL__N__e19a5351_28_scream_cxx_f90_interface_cpp_babe8b2b::fpe_guard_wrapper<scream_init_atm(int, int, int, int)::<lambda()> >(const <lambda()> &) (f=...) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp:51
#29 0x000000001024ad6c in scream_init_atm (run_start_ymd=10101, run_start_tod=0, case_start_ymd=10101, case_start_tod=0) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp:164
#30 0x0000000010246684 in atm_comp_mct::atm_init_mct (eclock=..., cdata=..., x2a=..., a2x=..., nlfilename=..., _nlfilename=6) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/src/mct_coupling/atm_comp_mct.F90:174
#31 0x000000001006823c in component_mod::component_init_cc (eclock=..., comp=..., comp_init=0x102444e0 <atm_comp_mct::atm_init_mct>, infodata=..., nlfilename=..., seq_flds_x2c_fluxes=..., seq_flds_c2x_fluxes=..., _nlfilename=6, _seq_flds_x2c_fluxes=0, _seq_flds_c2x_fluxes=0)
    at /gpfs/alpine/cli115/scratch/sarat/repos/scream/driver-mct/main/component_mod.F90:248
#32 0x00000000100473f0 in cime_comp_mod::cime_init () at /gpfs/alpine/cli115/scratch/sarat/repos/scream/driver-mct/main/cime_comp_mod.F90:1438
#33 0x000000001005fa40 in cime_driver () at /gpfs/alpine/cli115/scratch/sarat/repos/scream/driver-mct/main/cime_driver.F90:122
#34 0x000000001005fbf0 in main (argc=1, argv=0x7fffd9044d20) at /gpfs/alpine/cli115/scratch/sarat/repos/scream/driver-mct/main/cime_driver.F90:23
#35 0x00002000060e4078 in generic_start_main.isra () from /lib64/power9/libc.so.6
#36 0x00002000060e4264 in __libc_start_main () from /lib64/power9/libc.so.6
#37 0x0000000000000000 in ?? ()N
```

**Comment by bartgol** [comment]
> v1 ne4 crashes during initialization using 2 tasks on a single node. We get a core dump
> 
> Even disabling GPU-aware MPI didn't help. I suspected GPU to GPU communication issue. So, I tried a flag to disable fast GPU Peer-to-peer communication but that still crashed (PAMI_DISABLE_IPC=1)

Did you also disable MPI on device in Home? If not, Homme is still trying to pass device pointers to the MPI routines, which would then have a legit reason to crash (i.e., an invalid pointer).

**Comment by PeterCaldwell** [comment]
I think the workaround for this is using Jim's old cuda and gnu versions. Can we close this, @sarats ?

**Comment by bartgol** [comment]
I vote for closing too, and maybe opening a more targeted "wishlist" issue where we discuss switching to cuda11 and gnu9, since we kind of think that the issue simply boiled down to module versions.

**Comment by sarats** [comment]
Let's close this as it stems from module versions
