### ISSUE TITLE
MPI hangs with ne30 on pm-cpu with more MPI's

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1745]
With ne30 problems `F2010-SCREAMv1-noAero.ne30_ne30` I'm hitting MPI hangs on pm-cpu. Doesn't need to be without spa.  Most cases are OK, but as I increase node count and MPI's this happens.

I can see where it's stopped which is:

```
#0  0x0000148e664501a9 in MPIDI_SHMI_progress () from /opt/cray/pe/lib64/libmpi_gnu_91.so.12
#1  0x0000148e64f689d9 in MPIR_Waitall_impl () from /opt/cray/pe/lib64/libmpi_gnu_91.so.12
#2  0x0000148e64fced71 in MPIR_Waitall () from /opt/cray/pe/lib64/libmpi_gnu_91.so.12
#3  0x0000148e64fd026e in PMPI_Waitall () from /opt/cray/pe/lib64/libmpi_gnu_91.so.12
#4  0x0000148e66c7216e in pmpi_waitall__ () from /opt/cray/pe/lib64/libmpifort_gnu_91.so.12
#5  0x0000000000c33890 in ice_boundary::ice_haloupdate2dr8 (array=..., halo=..., fieldloc=1, fieldkind=1, fillvalue=<optimized out>) at /global/cfs/cdirs/e3sm/ndk/se09-jun13/components/cice/src/mpi/ice_boundary.F90:1479
#6  0x0000000000c723bc in ice_grid::makemask () at /global/cfs/cdirs/e3sm/ndk/se09-jun13/components/cice/src/source/ice_grid.F90:1657
#7  0x0000000000c74493 in ice_grid::latlongrid () at /global/cfs/cdirs/e3sm/ndk/se09-jun13/components/cice/src/source/ice_grid.F90:1265
#8  0x0000000000c779e2 in ice_grid::init_grid2 () at /global/cfs/cdirs/e3sm/ndk/se09-jun13/components/cice/src/source/ice_grid.F90:338
#9  0x0000000000cc79d8 in cice_initmod::cice_init (mpicom_ice=-1006632930) at /global/cfs/cdirs/e3sm/ndk/se09-jun13/components/cice/src/drivers/cpl/CICE_InitMod.F90:109
#10 0x0000000000c0dd29 in ice_comp_mct::ice_init_mct (eclock=..., cdata_i=..., x2i_i=..., i2x_i=..., nlfilename=..., _nlfilename=_nlfilename@entry=6) at /global/cfs/cdirs/e3sm/ndk/se09-jun13/components/cice/src/drivers/cpl/ice_comp_mct.F90:242
#11 0x00000000004bed35 in component_mod::component_init_cc (eclock=..., comp=..., comp_init=0xc0d260 <ice_comp_mct::ice_init_mct>, infodata=..., nlfilename=..., seq_flds_x2c_fluxes=..., seq_flds_c2x_fluxes=..., _nlfilename=6, 
    _seq_flds_x2c_fluxes=0, _seq_flds_c2x_fluxes=0) at /global/cfs/cdirs/e3sm/ndk/se09-jun13/driver-mct/main/component_mod.F90:258
#12 0x00000000004af3b7 in cime_comp_mod::cime_init () at /global/cfs/cdirs/e3sm/ndk/se09-jun13/driver-mct/main/cime_comp_mod.F90:1462
#13 0x000000000048b5dd in cime_driver () at /global/cfs/cdirs/e3sm/ndk/se09-jun13/driver-mct/main/cime_driver.F90:122
#14 main (argc=<optimized out>, argv=<optimized out>) at /global/cfs/cdirs/e3sm/ndk/se09-jun13/driver-mct/main/cime_driver.F90:23
#15 0x0000148e62bcc2bd in __libc_start_main () from /lib64/libc.so.6
#16 0x00000000004a0aea in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by ndkeen** [comment]
closing and merging with https://github.com/E3SM-Project/scream/issues/1731
