### ISSUE TITLE
Floating-point exception with DEBUG case on pm-cpu (rho_zt has zero in shoc_dp_inverse_impl.hpp)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1793]
I had not tried DEBUG in a while and perhaps still something I've got wrong.

This test fails with threading:
```
SMS_D_P512x2.ne30_ne30.F2010-SCREAMv1-noAero
```
but not this one
```
SMS_D_P512x1.ne30_ne30.F2010-SCREAMv1-noAero
```

where the non-DEBUG cases are OK.

with: 

```
  0: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
  0: 
  0: Backtrace for this error:
  0: #0  0x1499f3f20d6f in ???
  0: E3SM-Project/scream#1  0x3229ba0 in _ZN4ekatdvIdLi16EiEENS_4PackIT_XT0_EEERKT1_RKS3_
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/externals/ekat/src/ekat/ekat_pack.hpp:358
  0: E3SM-Project/scream#2  0x3229ba0 in _ZZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE10dp_inverseERKNS2_4Impl20HostThreadTeamMemberIS4_EERKiRKNS2_4ViewIPKN4ekat4PackIdLi16EEEJNS2_11LayoutRightES6_NS2_12MemoryTraitsILj1EEEEEESQ_RKNSF_IPSI_JSL_S6_SN_EEEENKUlSE_E_clESE_
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/components/scream/src/physics/shoc/shoc_dp_inverse_impl.hpp:23
  0: E3SM-Project/scream#3  0x3229cb7 in _ZN6Kokkos12parallel_forIiZN6scream4shoc9FunctionsIdNS_6DeviceINS_6OpenMPENS_9HostSpaceEEEE10dp_inverseERKNS_4Impl20HostThreadTeamMemberIS5_EERKiRKNS_4ViewIPKN4ekat4PackIdLi16EEEJNS_11LayoutRightES7_NS_12MemoryTraitsILj1EEEEEESR_RKNSG_IPSJ_JSM_S7_SO_EEEEUlSF_E_SB_EEvRKNS9_31TeamThreadRangeBoundariesStructIT_T1_EERKT0_PPKNSt9enable_ifIXsrNS9_26is_host_thread_team_memberISZ_EE5valueEvE4typeE
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/externals/ekat/extern/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:766
  0: E3SM-Project/scream#4  0x3229895 in _ZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE10dp_inverseERKNS2_4Impl20HostThreadTeamMemberIS4_EERKiRKNS2_4ViewIPKN4ekat4PackIdLi16EEEJNS2_11LayoutRightES6_NS2_12MemoryTraitsILj1EEEEEESQ_RKNSF_IPSI_JSL_S6_SN_EEE
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/components/scream/src/physics/shoc/shoc_dp_inverse_impl.hpp:22
  0: E3SM-Project/scream#5  0x32174da in _ZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE27update_prognostics_implicitERKNS2_4Impl20HostThreadTeamMemberIS4_EERKiSE_SE_RKdRKNS2_4ViewIPKN4ekat4PackIdLi16EEEJNS2_11LayoutRightES6_NS2_12MemoryTraitsILj1EEEEEESS_SS_SS_SS_SS_SS_SG_SG_SG_SG_SS_RKNSI_16WorkspaceManagerISK_S6_E9WorkspaceERKNSH_IPSK_JSN_S6_SP_EEES11_RKNSH_IPSY_JSN_S6_SP_EEES11_S11_S11_
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/components/scream/src/physics/shoc/shoc_update_prognostics_implicit_impl.hpp:100
  0: E3SM-Project/scream#6  0x31ea8af in _ZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE18shoc_main_internalERKNS2_4Impl20HostThreadTeamMemberIS4_EERKiSE_SE_SE_SE_RKdSG_SG_RKNS2_4ViewIPKN4ekat4PackIdLi16EEEJNS2_11LayoutRightES6_NS2_12MemoryTraitsILj1EEEEEESS_SS_SS_SS_SS_SS_SG_SG_SG_SG_SS_SS_SG_RKNSI_16WorkspaceManagerISK_S6_E9WorkspaceERKNSH_IPSK_JSN_S6_SP_EEES11_S11_S11_S11_S11_S11_RKNSH_IPSY_JSN_S6_SP_EEES11_S11_S11_RdS11_S11_S11_S11_S11_S11_S11_S11_S11_S11_S11_S11_S11_S11_S11_
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/components/scream/src/physics/shoc/shoc_main_impl.hpp:203
  0: E3SM-Project/scream#7  0x31e783b in _ZZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE9shoc_mainERKiS9_S9_S9_S9_S9_RKdRKN4ekat16WorkspaceManagerINSC_4PackIdLi16EEES6_EERKNS7_9SHOCInputERKNS7_15SHOCInputOutputERKNS7_10SHOCOutputERKNS7_17SHOCHistoryOutputEENKUlRKNS2_4Impl20HostThreadTeamMemberIS4_EEE_clESZ_
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/components/scream/src/physics/shoc/shoc_main_impl.hpp:364
  0: E3SM-Project/scream#8  0x31f04f0 in _ZN6Kokkos4Impl11ParallelForIZN6scream4shoc9FunctionsIdNS_6DeviceINS_6OpenMPENS_9HostSpaceEEEE9shoc_mainERKiSB_SB_SB_SB_SB_RKdRKN4ekat16WorkspaceManagerINSE_4PackIdLi16EEES8_EERKNS9_9SHOCInputERKNS9_15SHOCInputOutputERKNS9_10SHOCOutputERKNS9_17SHOCHistoryOutputEEUlRKNS0_20HostThreadTeamMemberIS6_EEE_NS_10TeamPolicyIJS6_EEES6_E9exec_teamIvEENSt9enable_ifIXsrSt7is_sameIT_vE5valueEvE4typeERKS11_RNS0_18HostThreadTeamDataEiii
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/externals/ekat/extern/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:867
  0: E3SM-Project/scream#9  0x31f51af in _ZNK6Kokkos4Impl11ParallelForIZN6scream4shoc9FunctionsIdNS_6DeviceINS_6OpenMPENS_9HostSpaceEEEE9shoc_mainERKiSB_SB_SB_SB_SB_RKdRKN4ekat16WorkspaceManagerINSE_4PackIdLi16EEES8_EERKNS9_9SHOCInputERKNS9_15SHOCInputOutputERKNS9_10SHOCOutputERKNS9_17SHOCHistoryOutputEEUlRKNS0_20HostThreadTeamMemberIS6_EEE_NS_10TeamPolicyIJS6_EEES6_E7executeEv._omp_fn.0
  0:    at /ascratch/sd/n/ndk/wacmy/s01-jul5/externals/ekat/extern/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:940
  0: E3SM-Project/scream#10  0x1499f8690a55 in gomp_thread_start
  0:    at ../../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/libgomp/team.c:125
  0: E3SM-Project/scream#11  0x1499f48396e9 in ???
  0: E3SM-Project/scream#12  0x1499f3feda8e in ???
  0: E3SM-Project/scream#13  0xffffffffffffffff in ???
```

**Comment by ambrad** [comment]
Would you check if the pack size is 1? In a debug build, it should be, but it would be good to check that's true.

**Comment by ndkeen** [comment]
I now realize this may be the same issue as https://github.com/E3SM-Project/scream/issues/1694

**Comment by ndkeen** [comment]
closing as it seems related to issue noted above
