### ISSUE TITLE
With ne1024, runtime error in init: check_downscale_consistency ERROR: column-level forcing differs from gridcell-level forcing for urban point

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1844]
I'm trying a ne1024 case on pm-cpu with: 
```
set compset=F2010-SCREAMv1-noAero
set res=ne1024np4_oRRS15to5
```

and it uses latest ne1024 file:
```
./atmchange Vertical__Coordinate__Filename="/global/cfs/cdirs/e3sm/inputdata/atm/scream/init/screami_ne1024np4L128_20220721.nc"
./atmchange Initial__Conditions::Filename="/global/cfs/cdirs/e3sm/inputdata/atm/scream/init/screami_ne1024np4L128_20220721.nc"
```

Stops in init:

```
    0: [EAMxx] initialize_atm_procs ... done!
    0: [EAMxx::init] resolution-dependent device memory footprint: 423.123624MB
    0: MCT::m_Router::initp_: GSMap indices not increasing...Will correct
    0: MCT::m_Router::initp_: RGSMap indices not increasing...Will correct
    0: MCT::m_Router::initp_: RGSMap indices not increasing...Will correct
    0: MCT::m_Router::initp_: GSMap indices not increasing...Will correct
    0:  ERROR: Unknown error submitted to shr_abort_abort.
    0:  ERROR: Unknown error submitted to shr_abort_abort.
    0: #0  0xd83d6a in __shr_abort_mod_MOD_shr_abort_backtrace
    0: #0  0xd83d6a in __shr_abort_mod_MOD_shr_abort_backtrace
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/share/util/shr_abort_mod.F90:104
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/share/util/shr_abort_mod.F90:104
    0: #1  0xd83f3c in __shr_abort_mod_MOD_shr_abort_abort
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/share/util/shr_abort_mod.F90:61
    0: #1  0xd83f3c in __shr_abort_mod_MOD_shr_abort_abort
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/share/util/shr_abort_mod.F90:61
    0: #2  0xb45a7b in check_downscale_consistency
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/components/elm/src/main/atm2lndMod.F90:440
    0: #2  0xb45a7b in check_downscale_consistency
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/components/elm/src/main/atm2lndMod.F90:440
    0: #3  0x570c88 in __elm_driver_MOD_elm_drv._omp_fn.4
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/components/elm/src/main/elm_driver.F90:650
    0: #4  0x14bc402d8295 in GOMP_parallel
    0:  at ../../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/libgomp/parallel.c:178
    0: #5  0x57621f in __elm_driver_MOD_elm_drv
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/components/elm/src/main/elm_driver.F90:633
    0: #6  0x55efb9 in __lnd_comp_mct_MOD_lnd_run_mct
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/components/elm/src/cpl/lnd_comp_mct.F90:512
    0: #7  0x4c8cf8 in __component_mod_MOD_component_run
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/driver-mct/main/component_mod.F90:751
    0: #3  0x570c88 in __elm_driver_MOD_elm_drv._omp_fn.4
    0:  at /global/cfs/cdirs/e3sm/ndk/se13-jul29/components/elm/src/main/elm_driver.F90:650
    0: #4  0x14bc402e0a55 in gomp_thread_start
    0:  at ../../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/libgomp/team.c:125
```

And in homme_atm.log file:
```
 check_downscale_consistency ERROR: column-level forcing differs from gridcell-level forcing for urban point
 c, g =    156766448    10562115
 ENDRUN:ERROR in /global/cfs/cdirs/e3sm/ndk/se13-jul29/components/elm/src/main/atm2lndMod.F90 at line 440                                                                               $
 ERROR: Unknown error submitted to shr_abort_abort.
 check_downscale_consistency ERROR: column-level forcing differs from gridcell-level forcing for urban point
 c, g =    156752068    10561257
 ENDRUN:ERROR in /global/cfs/cdirs/e3sm/ndk/se13-jul29/components/elm/src/main/atm2lndMod.F90 at line 440                                                                               $
 ERROR: Unknown error submitted to shr_abort_abort.
   1023
 proc=         8191  clump no =            1  clump id=         8192  beg topounit=     16758133  end topounit=     16759155  total topounits per clump =         1023
 proc=         8191  clump no =            1  clump id=         8192  beg landunit=     65783934  end landunit=     65787922  total landunits per clump =         3989
 proc=         8191  clump no =            1  clump id=         8192  beg column  =    248638086  end column  =    248653102  total columns per clump  =        15017
 proc=         8191  clump no =            1  clump id=         8192  beg pft     =    516768198  end pft     =    516799582  total pfts per clump     =        31385
 proc=         8191  clump no =            1  clump id=         8192  beg cohort     =     16758133  end cohort     =     16759155  total cohorts per clump     =         1023
 nu_q      =  0.34E-07
viscosity:  nu_p      =  0.34E-07
viscosity:  nu_top      =  0.10E+05
viscosity:  tom_sponge_start  =  0.00E+00
 Running dycore: theta-l
 Running tracer transport method: horizonatally Eulerian
 Initializing dynamics grid...
 total number of elements nelem =      6291456
 getMetaSchedule: tmpP:            5           1           3          95       18205         142           1         236       18206        3698           2        3699       14564    $
 prim_init1: total threads: nthreads =            0
 threads across elements    hthreads =            1
 threading within elements  vthreads =            1
 init shared boundary_exchange buffers
 initializing elements...
 running mass_matrix
Epsilon bubble correction: Corrected area - domain size  0.00000000000122036
 re-running mass_matrix
 running global_dof
 INFO: Non-scalable action: Computing global coords in SE dycore.
 INFO: Non-scalable action: Computing global area in SE dycore.
1 Layer Locations (*1000)
   1       NaN                 NaN                 NaN
                     NaN                 NaN                 NaN
   2       NaN                 NaN                 NaN
                     NaN                 NaN                 NaN
   3       NaN                 NaN                 NaN
                     NaN                 NaN                 NaN
```

In `components/elm/src/main/atm2lndMod.F90`:
```
      ! Make sure that, for urban points, the column-level forcing fields are identical to                                                                                               
      ! the gridcell-level forcing fields. This is needed because the urban-specific code                                                                                                
      ! sometimes uses the gridcell-level forcing fields (and it would take a large                                                                                                      
      ! refactor to change this to use column-level fields).                                                                                                                             

      do c = bounds%begc, bounds%endc
         if (col_pp%active(c)) then
            l = col_pp%landunit(c)
            g = col_pp%gridcell(c)

            if (lun_pp%urbpoi(l)) then
               if (forc_t_c(c)     /= forc_t_g(g)    .or. &
                    forc_th_c(c)    /= forc_th_g(g)   .or. &
                    forc_q_c(c)     /= forc_q_g(g)    .or. &
                    forc_pbot_c(c)  /= forc_pbot_g(g) .or. &
                    forc_rho_c(c)   /= forc_rho_g(g)  .or. &
                    forc_rain_c(c)  /= forc_rain_g(g) .or. &
                    forc_snow_c(c)  /= forc_snow_g(g) .or. &
                    forc_lwrad_c(c) /= forc_lwrad_g(g)) then
                  write(iulog,*) subname//' ERROR: column-level forcing differs from gridcell-level forcing for urban point'
                  write(iulog,*) 'c, g = ', c, g
                  call endrun(msg=errMsg(__FILE__, __LINE__))
               end if  ! inequal                                                                                                                                                         
            end if  ! urbpoi                                                                                                                                                             
         end if  ! active                                                                                                                                                                
      end do
```

**Comment by AaronDonahue** [comment]
@ndkeen , thank you for updating us on the status of ne1024 initial run.  That looks like something is going wrong right off the bat with the pressure levels all being NaN.

**Comment by brhillman** [comment]
The problem is the initial condition is corrupted...again. I'll fix.

**Comment by ndkeen** [comment]
Using latest `/global/cfs/cdirs/e3sm/inputdata/atm/scream/init/screami_ne1024np4L128_20220805.nc`, I no longer see this issue. I do now see a different problem and will make a separate issue.
