### ISSUE TITLE
Problem building on chrysalis

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2001]
Using scream master of Oct26th.
With `SMS.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_gnu`, I see a problem with the build.
While the build completes and writes `e3sm.exe`, something that tests that the build is completed
must not be working as the job is not submitted. Trying case.build again:

```
model_only is True
building scream
scream cmake options: ' -DSCREAM_NP=4 -DSCREAM_NUM_VERTICAL_LEV=72 -DSCREAM_NUM_TRACERS=10 -DSCREAM_DYN_TARGET=theta-l_kokkos -DSCREAM_CIME_BUILD=ON'
Configuring full e3sm model with output to file /lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s08-oct26/SMS.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_gnu.20221026_181158_6mpg5a/bld/e3sm.bldlog.221026-182809
   Calling cmake directly, see top of log file for specific call
Building e3sm model with output to file /lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s08-oct26/SMS.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_gnu.20221026_181158_6mpg5a/bld/e3sm.bldlog.221026-182809
   Calling make, see top of log file for specific call
Traceback (most recent call last):
  File "case.build", line 256, in <module>
    _main_func(__doc__)
  File "case.build", line 236, in _main_func
    separate_builds=separate_builds,
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime/CIME/SystemTests/system_tests_common.py", line 130, in build
    model_only=(phase_name == MODEL_BUILD_PHASE),
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime/CIME/SystemTests/system_tests_common.py", line 165, in build_phase
    self.build_indv(sharedlib_only=sharedlib_only, model_only=model_only)
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime/CIME/SystemTests/system_tests_common.py", line 180, in build_indv
    separate_builds=self._user_separate_builds,
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime/CIME/build.py", line 1292, in case_build
    return run_and_log_case_status(functor, cb, caseroot=caseroot)
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime/CIME/utils.py", line 2433, in run_and_log_case_status
    rv = func()
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime/CIME/build.py", line 1285, in <lambda>
    dry_run,
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime/CIME/build.py", line 1224, in _case_build_impl
    save_build_provenance=save_build_provenance,
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime/CIME/build.py", line 1249, in post_build
    Config.instance().save_build_provenance(case, lid=lid)
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime_config/customize/provenance.py", line 24, in save_build_provenance
    _record_git_provenance(srcroot, exeroot, lid)
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime_config/customize/provenance.py", line 68, in _record_git_provenance
    _run_git_cmd_recursively("diff", srcroot, diff_prov)
  File "/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/cime_config/customize/provenance.py", line 162, in _run_git_cmd_recursively
    fd.write((output2 if rc2 == 0 else err2) + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 392: ordinal not in range(128)
6.752u 65.615s 4:54.59 24.5% 0+0k 0+168io 0pf+0w 139500mem
```

**Comment by ndkeen** [comment]
With Intel build, I also get a fail, but it's an internal compiler error

```
In file included from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/externals/ekat/extern/kokkos/core/src/Kokkos_Tuners.hpp(51),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/externals/ekat/extern/kokkos/core/src/impl/Kokkos_Tools_Generic.hpp(53),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/externals/ekat/extern/kokkos/core/src/Kokkos_Parallel.hpp(57),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/externals/ekat/extern/kokkos/core/src/Kokkos_Serial.hpp(59),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/externals/ekat/extern/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp(49),
                 from /lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s09-oct26/SMS_P1024.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_intel.20221026_182652_k389nr/bld/cmake-bld/externals/kokkos/KokkosCore_Config_DeclareBackend.hpp(47),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/externals/ekat/extern/kokkos/core/src/Kokkos_Core.hpp(53),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/externals/ekat/src/ekat/ekat.hpp(6),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/components/scream/src/share/scream_types.hpp(4),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/components/scream/src/share/util/scream_utils.hpp(4),
                 from /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/components/scream/src/share/util/scream_utils.cpp(1):
/lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/externals/ekat/extern/kokkos/core/src/KokkosExp_MDRangePolicy.hpp(389): warning #2651: attribute does not apply to any entity
  using Iterate KOKKOS_DEPRECATED = Kokkos::Iterate;
                ^

Target CMakeFiles/scream_share.dir/util/scream_utils.cpp.o built in 1.737871 seconds
": internal error: 101003_1112

compilation aborted for /lcrc/group/e3sm/ac.ndkeen/wacmy/s09-oct26/components/homme/src/share/compose/compose_cedr_sl_run_check.cpp (code 4)
Target CMakeFiles/composec++.dir/compose_cedr_sl_run_check.cpp.o built in 17.053695 seconds
make[2]: *** [scream/src/dynamics/homme/homme/composec++/CMakeFiles/composec++.dir/build.make:319: scream/src/dynamics/homme/homme/composec++/CMakeFiles/composec++.dir/compose_cedr_sl_run_check.cpp.o] Error 4
make[2]: Leaving directory '/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s09-oct26/SMS_P1024.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_intel.20221026_182652_k389nr/bld/cmake-bld'
make[1]: *** [CMakeFiles/Makefile2:2235: scream/src/dynamics/homme/homme/composec++/CMakeFiles/composec++.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Target CMakeFiles/scream_share.dir/property_checks/mass_and_energy_column_conservation_check.cpp.o built in 12.188427 seconds
": internal error: 101003_1112
```

**Comment by ndkeen** [comment]
With Nov 9th repo, I don't see this build error.  It did seem odd and had meant to try again sooner.
