### ISSUE TITLE
FPE with SMS_D_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_gnu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2147]
Using Feb 1st repo and `SMS_D_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_gnu` I see:

```
 0:  number of MPI processes per node: min,max=          64          64
 0:
 0:
 0: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
 0:
 0: Backtrace for this error:
 0: #0  0x151dfd023d6f in ???
 0: #1  0x2d7b52a in operator/<double, Kokkos::OpenMP, 16>
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/components/homme/src/share/cxx/vector/KokkosKernels_Vector_SIMD.hpp:372
 0: #2  0x2d7b52a in operator/<double, Kokkos::OpenMP, 16>
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/components/homme/src/share/cxx/vector/KokkosKernels_Vector_SIMD.hpp:390
 0: #3  0x2d7b52a in _ZN5Homme15EquationOfState23pressure_to_recip_exnerIN13KokkosKernels7Batched12Experimental6VectorINS4_9VectorTagINS4_4SIMDIdN6Kokkos6OpenMPEEELi16EEEEEEEvRT_
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/components/homme/src/theta-l_kokkos/cxx/EquationOfState.hpp:49
 0: #4  0x2d56148 in operator()
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/components/homme/src/share/cxx/GllFvRemapImpl.cpp:489
 0: #5  0x2d65bc0 in parallel_for<int, Homme::GllFvRemapImpl::run_dyn_to_fv_phys(int, const Phys1T&, const Phys1T&, const Phys2T&, const Phys2T&, const Phys3T&, const Phys3T&, const Phys2T*)::<lambda(const MT&)>::<lambda(int)>::<lambda(int)>, Kokkos::Impl::HostThreadTeamMember<Kokkos::OpenMP> >
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/externals/ekat/extern/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:780
 0: #6  0x2d56954 in operator()
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/components/homme/src/share/cxx/GllFvRemapImpl.cpp:487
 0: #7  0x2d65c46 in parallel_for<int, Homme::GllFvRemapImpl::run_dyn_to_fv_phys(int, const Phys1T&, const Phys1T&, const Phys2T&, const Phys2T&, const Phys3T&, const Phys3T&, const Phys2T*)::<lambda(const MT&)>::<lambda(int)>, Kokkos::Impl::HostThreadTeamMember<Kokkos::OpenMP> >
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/externals/ekat/extern/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:764
 0: #8  0x2d5853b in operator()
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/components/homme/src/share/cxx/GllFvRemapImpl.cpp:493
 0: #9  0x2d6f07a in exec_team<void>
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/externals/ekat/extern/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:934
 0: #10  0x2d70d59 in _ZNK6Kokkos4Impl11ParallelForIZN5Homme14GllFvRemapImpl18run_dyn_to_fv_physEiRKNS_4ViewIPPdJNS_11LayoutRightENS_9HostSpaceENS_12MemoryTraitsILj9EEEEEESD_RKNS4_IPS6_JS7_S8_SA_EEESH_RKNS4_IPSE_JS7_S8_SA_EEESL_PSG_EUlRKNS0_20HostThreadTeamMemberINS_6OpenMPEEEE_NS_10TeamPolicyIJ\
SO_EEESO_E7executeEv._omp_fn.0
 0:     at /global/cfs/cdirs/e3sm/ndk/repos/scream-afterPR2143-6d7d4f766c/externals/ekat/extern/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:1004
 0: #11  0x151e017a9afd in gomp_thread_start
 0:     at ../../../cpe-gcc-12.1.0-202208101649.1dfb26392197c/libgomp/team.c:129
 0: #12  0x151dfd9426e9 in ???
 0: #13  0x151dfd0f0a8e in ???
 0: #14  0xffffffffffffffff in ???
srun: error: nid004438: task 0: Floating point exception
srun: launch/slurm: _step_signal: Terminating StepId=5220286.0
 0: slurmstepd: error: *** STEP 5220286.0 ON nid004438 CANCELLED AT 2023-02-03T00:43:02 ***
```

**Comment by ndkeen** [comment]
I need to redo the issue
