### ISSUE TITLE
Initial issues running on tioga

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2366]
I'm currently hitting what looks like a hang on tioga with ne4 and 1 MPI/GPU.

`SMS_D_P1x1_Ld1.ne4pg2_ne4pg2.F2010-SCREAMv1.tioga_craygpu`

I can see stack with gdb

```
#0  0x000015553f066868 in rocr::core::InterruptSignal::WaitRelaxed(hsa_signal_condition_t, long, unsigned long, hsa_wait_state_t) () from /opt/rocm-5.4.3/lib/libhsa-runtime64.so.1
#1  0x000015553f06672a in rocr::core::InterruptSignal::WaitAcquire(hsa_signal_condition_t, long, unsigned long, hsa_wait_state_t) () from /opt/rocm-5.4.3/lib/libhsa-runtime64.so.1
#2  0x000015553f05ce81 in rocr::HSA::hsa_signal_wait_scacquire(hsa_signal_s, hsa_signal_condition_t, long, unsigned long, hsa_wait_state_t) () from /opt/rocm-5.4.3/lib/libhsa-runtime64.so.1
#3  0x000015555339223b in roc::Device::IsHwEventReady(amd::Event const&, bool) const () from /opt/rocm-5.4.3/lib/libamdhip64.so.5
#4  0x0000155553382682 in amd::HostQueue::finish() () from /opt/rocm-5.4.3/lib/libamdhip64.so.5
#5  0x00001555532ed481 in hipStreamSynchronize_common(ihipStream_t*) () from /opt/rocm-5.4.3/lib/libamdhip64.so.5
#6  0x00001555532ed639 in hipStreamSynchronize () from /opt/rocm-5.4.3/lib/libamdhip64.so.5
#7  0x0000000002ed9e75 in Kokkos::Experimental::Impl::HIPInternal::fence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#8  0x0000000002a3f4ae in Kokkos::Experimental::Impl::HIPParallelLaunch<Kokkos::Impl::ParallelFor<scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::p3_main(scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3PrognosticState const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticInputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticOutputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3Infrastructure const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3HistoryOnly const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3LookupTables const&, ekat::WorkspaceManager<ekat::Pack<double, 1>, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> > const&, int, int)::{lambda(Kokkos::Impl::HIPTeamMember const&)#1}, Kokkos::TeamPolicy<Kokkos::Experimental::HIP>, Kokkos::Experimental::HIP>, Kokkos::LaunchBounds<0u, 0u>, (Kokkos::Experimental::Impl::HIPLaunchMechanism)1>::HIPParallelLaunch(Kokkos::TeamPolicy<Kokkos::Experimental::HIP> const&, dim3 const&, dim3 const, int, Kokkos::Experimental::Impl::HIPInternal const*, bool) ()
#9  0x0000000002a3e786 in Kokkos::Impl::ParallelFor<scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::p3_main(scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3PrognosticState const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticInputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticOutputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3Infrastructure const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3HistoryOnly const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3LookupTables const&, ekat::WorkspaceManager<ekat::Pack<double, 1>, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> > const&, int, int)::{lambda(Kokkos::Impl::HIPTeamMember const&)#1}, Kokkos::TeamPolicy<Kokkos::Experimental::HIP>, Kokkos::Experimental::HIP>::execute() const ()
#10 0x0000000002a3a767 in void Kokkos::parallel_for<Kokkos::TeamPolicy<Kokkos::Experimental::HIP>, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::p3_main(scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3PrognosticState const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticInputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticOutputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3Infrastructure const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3HistoryOnly const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3LookupTables const&, ekat::WorkspaceManager<ekat::Pack<double, 1>, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> > const&, int, int)::{lambda(Kokkos::Impl::HIPTeamMember const&)#1}, void>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Kokkos::TeamPolicy<Kokkos::Experimental::HIP> const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::p3_main(scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3PrognosticState const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticInputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticOutputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3Infrastructure const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3HistoryOnly const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3LookupTables const&, ekat::WorkspaceManager<ekat::Pack<double, 1>, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> > const&, int, int)::{lambda(Kokkos::Impl::HIPTeamMember const&)#1} const&) ()
#11 0x0000000002a38b8f in scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::p3_main(scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3PrognosticState const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticInputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3DiagnosticOutputs const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3Infrastructure const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3HistoryOnly const&, scream::p3::Functions<double, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> >::P3LookupTables const&, ekat::WorkspaceManager<ekat::Pack<double, 1>, Kokkos::Device<Kokkos::Experimental::HIP, Kokkos::Experimental::HIPSpace> > const&, int, int) ()
#12 0x0000000002a34c8c in scream::P3Microphysics::run_impl(double) ()
#13 0x0000000002d139a7 in scream::AtmosphereProcess::run(double) ()
#14 0x0000000002d6275b in scream::AtmosphereProcessGroup::run_sequential(double) ()
#15 0x0000000002d139a7 in scream::AtmosphereProcess::run(double) ()
#16 0x0000000002d6275b in scream::AtmosphereProcessGroup::run_sequential(double) ()
#17 0x0000000002d139a7 in scream::AtmosphereProcess::run(double) ()
#18 0x0000000002d6275b in scream::AtmosphereProcessGroup::run_sequential(double) ()
#19 0x0000000002d139a7 in scream::AtmosphereProcess::run(double) ()
#20 0x00000000022fba41 in scream::control::AtmosphereDriver::run(int) ()
#21 0x00000000006273ec in scream_run ()
#22 0x000000000062192b in atm_run_mct$atm_comp_mct_ ()
#23 0x000000000047df95 in component_run$component_mod_ ()
#24 0x0000000000452656 in cime_run$cime_comp_mod_ ()
#25 0x0000000000471180 in main ()
```

**Comment by ndkeen** [comment]
Not working on this machine recently, so surely this is resolved or different now.
