### ISSUE TITLE
MPAS-Sea Ice error while running fully coupled compset with EAMxx

### ISSUE THREAD

**Issue by singhbalwinder** [E3SM-Project/scream#2470]
The fully coupled compset when run with compset `WCYCLXX2010` and grid `ne1024pg2_oRRS18to6v3` on PM-GPU, runs up to:
```
Atmosphere step = 538
  model time = 0001-01-01 14:56:40
``` 
After that, it blows up with the following error (output only from 1080 proc):
```
1080: 
1080: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
1080: 
1080: Backtrace for this error:
1080: #0  0x1499902a1d4f in ???
1080: #1  0x2c30e5d in compute_barycenter_coordinates
1080:   at /pscratch/sd/b/bsingh/e3sm_scratch/pm-gpu/SMS_D.ne1024pg2_oRRS18to6v3.WCYCLXX2010.pm-gpu_gnugpu.scr_cime_test/bld/cmake-bld/core_seaice/shared/mpas_seaice_advection_incremental_remap.f90:4740
1080: #2  0x2c4e042 in construct_linear_tracer_fields
1080:   at /pscratch/sd/b/bsingh/e3sm_scratch/pm-gpu/SMS_D.ne1024pg2_oRRS18to6v3.WCYCLXX2010.pm-gpu_gnugpu.scr_cime_test/bld/cmake-bld/core_seaice/shared/mpas_seaice_advection_incremental_remap.f90:3853
1080: #3  0x2c66b3b in incremental_remap_block
1080:   at /pscratch/sd/b/bsingh/e3sm_scratch/pm-gpu/SMS_D.ne1024pg2_oRRS18to6v3.WCYCLXX2010.pm-gpu_gnugpu.scr_cime_test/bld/cmake-bld/core_seaice/shared/mpas_seaice_advection_incremental_remap.f90:3067
1080: #4  0x2c68f79 in __seaice_advection_incremental_remap_MOD_seaice_run_advection_incremental_remap
1080:   at /pscratch/sd/b/bsingh/e3sm_scratch/pm-gpu/SMS_D.ne1024pg2_oRRS18to6v3.WCYCLXX2010.pm-gpu_gnugpu.scr_cime_test/bld/cmake-bld/core_seaice/shared/mpas_seaice_advection_incremental_remap.f90:2575
1080: #5  0x21ef08c in __seaice_advection_MOD_seaice_run_advection
1080:   at /pscratch/sd/b/bsingh/e3sm_scratch/pm-gpu/SMS_D.ne1024pg2_oRRS18to6v3.WCYCLXX2010.pm-gpu_gnugpu.scr_cime_test/bld/cmake-bld/core_seaice/shared/mpas_seaice_advection.f90:138
1080: #6  0x21eee49 in __seaice_time_integration_MOD_seaice_timestep
1080:   at /pscratch/sd/b/bsingh/e3sm_scratch/pm-gpu/SMS_D.ne1024pg2_oRRS18to6v3.WCYCLXX2010.pm-gpu_gnugpu.scr_cime_test/bld/cmake-bld/core_seaice/shared/mpas_seaice_time_integration.f90:159
1080: #7  0x2072103 in __ice_comp_mct_MOD_ice_run_mct
1080:   at /pscratch/sd/b/bsingh/e3sm_scratch/pm-gpu/SMS_D.ne1024pg2_oRRS18to6v3.WCYCLXX2010.pm-gpu_gnugpu.scr_cime_test/mpas-seaice/driver/ice_comp_mct.f90:1136
1080: #8  0x4881d4 in __component_mod_MOD_component_run
1080:   at /global/u2/b/bsingh/scream/srccode/scream/driver-mct/main/component_mod.F90:728
1080: #9  0x46be88 in __cime_comp_mod_MOD_cime_run
1080:   at /global/u2/b/bsingh/scream/srccode/scream/driver-mct/main/cime_comp_mod.F90:2897
1080: #10  0x4858da in cime_driver
1080:   at /global/u2/b/bsingh/scream/srccode/scream/driver-mct/main/cime_driver.F90:153
1080: #11  0x48593d in main
1080:   at /global/u2/b/bsingh/scream/srccode/scream/driver-mct/main/cime_driver.F90:23
srun: error: nid003276: task 1080: Floating point exception
```

Since it might be useful to look at the entire log, I have created a gist of the log at: https://gist.github.com/singhbalwinder/9a80115d6d5d5064f0b4866f4db393e5

The case name is:`SMS_D.ne1024pg2_oRRS18to6v3.WCYCLXX2010.pm-gpu_gnugpu.scr_cime_test`

**Comment by singhbalwinder** [comment]
Tagging @PeterCaldwell and @AaronDonahue.

Please feel free to tag/include more as you see appropriate.

I have set up an F case with MPAS-SI with the same grid to see if it is reproducible with an F case. I don't have an allocation to run that case. I will ask for more hours and run it to see if it works or not.
