### ISSUE TITLE
free(): invalid size while writing restarts at ne1024 on frontier

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2688]
I'm seeing a reproducible error at ne1024 on frontier while writing restarts.  It may be that I've simply run out of memory as I know writing restarts uses more memory. These are tests with only 320 nodes. (Further evidence of this being memory issue is that similar checkout/case does work OK on pm-gpu with 512 nodes).

```
free(): invalid size
```

From core files:
````
(gdb) where
#0  slist_insert_head (list=0x0, item=0x4f77913c0) at ./include/ofi_list.h:410
#1  ofi_buf_free (buf=0x4f77913e0) at ./include/ofi_mem.h:406
#2  util_mr_entry_free (cache=0x1bde95e0, entry=0x4f77913e0) at prov/util/src/util_mr_cache.c:94
#3  0x00007fff34ff0eb0 in util_mr_free_entry (entry=0x4f77913e0, cache=0x1bde95e0) at prov/util/src/util_mr_cache.c:112
#4  util_mr_cache_create (entry=0x7ffffffbb640, info=0x7ffffffbb5b0, cache=0x1bde95e0) at prov/util/src/util_mr_cache.c:325
#5  ofi_mr_cache_search (cache=cache@entry=0x1bde95e0, attr=attr@entry=0x7ffffffbb670, entry=entry@entry=0x7ffffffbb640) at prov/util/src/util_mr_cache.c:385
#6  0x00007fff350296a6 in cxip_map_cache (md=0x7ffffffbb708, attr=0x7ffffffbb670, dom=0x1bde5440) at prov/cxi/src/cxip_iomm.c:351
#7  cxip_map (dom=dom@entry=0x1bde5440, buf=buf@entry=0x579c37ec0, len=len@entry=62914560, flags=flags@entry=0, md=md@entry=0x7ffffffbb708) at prov/cxi/src/cxip_iomm.c:560
#8  0x00007fff35013cb7 in cxip_recv_req_alloc (rxc=rxc@entry=0x1c3fb100, buf=buf@entry=0x579c37ec0, len=len@entry=62914560, cxip_req=cxip_req@entry=0x7ffffffbb758) at prov/cxi/src/cxip_msg.c:223
#9  0x00007fff3501efbc in cxip_recv_common (rxc=0x1c3fb100, buf=0x579c37ec0, len=62914560, desc=<optimized out>, src_addr=<optimized out>, tag=210453401345, ignore=246290604621824, context=0x9cd68b60, flags=16777216, tagged=true, comp_cntr=0x0) at prov/cxi/src/cxip_msg.c:4172
#10 0x00007fff3501f9db in cxip_trecv (fid_ep=<optimized out>, buf=<optimized out>, len=<optimized out>, desc=<optimized out>, src_addr=<optimized out>, tag=<optimized out>, ignore=246290604621824, context=0x9cd68b60) at prov/cxi/src/cxip_msg.c:5614
#11 0x00007fffe9878af6 in PMPI_Irecv () from /opt/cray/pe/mpich/8.1.26/ofi/crayclang/14.0/lib/libmpi_cray.so.12
#12 0x0000000002c46c6b in pio_swapm ()
#13 0x0000000002bfdf96 in compute_counts ()
#14 0x0000000002c001f2 in box_rearrange_create ()
#15 0x0000000002bf5df6 in PIOc_InitDecomp ()
#16 0x0000000002b8f091 in pio_initdecomp_internal$piolib_mod_ ()
#17 0x0000000002b8e602 in pio_initdecomp_dof_i8$piolib_mod_ ()
#18 0x0000000001c26234 in get_decomp$scream_scorpio_interface_ ()
#19 0x0000000001c1804b in set_decomp$scream_scorpio_interface_ ()
#20 0x0000000001c16fa5 in eam_pio_enddef$scream_scorpio_interface_ ()
#21 0x0000000001c3e796 in eam_pio_enddef_c2f ()
#22 0x0000000001c36660 in scream::scorpio::eam_pio_enddef(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#23 0x0000000001c48624 in scream::OutputManager::setup_file(scream::IOFileSpecs&, scream::IOControl const&) ()
#24 0x0000000001c4b128 in scream::OutputManager::run(scream::util::TimeStamp const&)::{lambda(scream::IOControl&, scream::IOFileSpecs&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}::operator()(scream::IOControl&, scream::IOFileSpecs&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#25 0x0000000001c49280 in scream::OutputManager::run(scream::util::TimeStamp const&) ()
#26 0x00000000019aa09c in scream::control::AtmosphereDriver::run(int) ()
#27 0x00000000006478bb in scream_run ()
#28 0x0000000000642a7f in atm_run_mct$atm_comp_mct_ ()
#29 0x000000000046c1ff in component_run$component_mod_ ()
#30 0x000000000044701a in cime_run$cime_comp_mod_ ()
#31 0x00000000004600a2 in main ()
````

`/lustre/orion/cli115/proj-shared/noel/e3sm_scratch/s05-jan25/dy2b-ne1024/seed/dy2b-ne1024.ne1024pg2_ne1024pg2.F2010-SCREAMv1-DYAMOND2.s05-jan25`

The last time I've tested writing restarts at ne1024 on frontier was with our Cess branch.
I have done many day-long tests at ne1024, but with restarts off.
I can write restarts with ne30 and ne256.

**Comment by ndkeen** [comment]
Yep, it completed with 512 nodes on frontier, closing.
