### ISSUE TITLE
Can no longer test Fortran-SCREAM on LC machines

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#332]
I can no longer use the testing framework in CIME when running tests on the Livermore Computing platform.  I do not have this problem on Cori-KNL. 

If I checkout the code directly following our latest upstream merge, git hash: 2157b4c8e077e76111685012c48d4866e2de89e3, I can still test.  SCREAM-master fails.  I've looked at the differences between these two commits and am at a loss explaining why LC testing is somehow broken.

The moment I switch to the next entry in the git history, or all the way to master, I get the following error whenever I issue a `./create_test` command,
```
Finished SETUP for test SMS_P36x1.ne4_ne4.FSCREAM-LR.quartz_intel.cam-force_smp in 4.739335 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/test_root/2020_04_02_22_42-cd2a4cc-200403_1002/SMS_P36x1.ne4_ne4.FSCREAM-LR.quartz_intel.cam-force_smp.2020_04_02_22_42-cd2a4cc-200403_1002
    Errors were:
        /p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/test_root/2020_04_02_22_42-cd2a4cc-200403_1002/SMS_P36x1.ne4_ne4.FSCREAM-LR.quartz_intel.cam-force_smp.2020_04_02_22_42-cd2a4cc-200403_1002/env_mach_specific.xml already exists, delete to replace
        /p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/test_root/2020_04_02_22_42-cd2a4cc-200403_1002/SMS_P36x1.ne4_ne4.FSCREAM-LR.quartz_intel.cam-force_smp.2020_04_02_22_42-cd2a4cc-200403_1002/env_mach_specific.xml already exists, delete to replace
        Traceback (most recent call last):
          File "./case.setup", line 62, in <module>
            _main_func(__doc__)
          File "./case.setup", line 59, in _main_func
            case.case_setup(clean=clean, test_mode=test_mode, reset=reset)
          File "/p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/scream/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 240, in case_setup
            run_and_log_case_status(functor, phase, caseroot=caseroot)
          File "/p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/scream/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1720, in run_and_log_case_status
            rv = func()
          File "/p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/scream/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 234, in <lambda>
            functor = lambda: _case_setup_impl(self, caseroot, clean, test_mode, reset)
          File "/p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/scream/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 218, in _case_setup_impl
            case.create_namelists()
          File "/p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/scream/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 90, in create_namelists
            run_sub_or_cmd(cmd, (caseroot), "buildnml", (self, caseroot, compname), case=self)
          File "/p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/scream/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 381, in run_sub_or_cmd
            getattr(mod, subname)(*subargs)
          File "/p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/scream/components/cam/cime_config/buildnml", line 214, in buildnml
            safe_copy(os.path.join(scream_data_dir, item), os.path.join(din_loc_root, "atm/cam/physprops"))
          File "/p/lustre2/donahue5/E3SM_simulations/SCREAM/developer_tests/scream/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 846, in safe_copy
            os.chmod(st.st_mode | statlib.S_IWRITE)
        TypeError: chmod() takes exactly 2 arguments (1 given)

Due to presence of batch system, create_test will exit before tests are complete.
```

**Comment by jgfouca** [comment]
Hey @AaronDonahue , what version of python are you using?

**Comment by AaronDonahue** [comment]
[donahue5@quartz380:developer_tests]$ python --version
Python 2.7.16

**Comment by jgfouca** [comment]
OK, you hit an unusual corner case in utils.safe_copy that was broken, I pushed a hotfix to CIME.

**Comment by AaronDonahue** [comment]
Wow, thanks for finding and fixing the problem so quickly.  I'm testing the hot-fix now.

**Comment by AaronDonahue** [comment]
That worked! Thanks @jgfouca
